### ISSUE TITLE
Mettez en place une stratégie de tests (par le Tech Lead)

### ISSUE THREAD

**Issue by Deyine** [josephherradi/OCP10sysUpgrade#3]
Après un code review de la V1 je me suis rendu compte que des tests unitaires n’ont pas été implémentés, on est donc hors des process de qualité sur cette release....

Pour la release qui est en cours de développement, merci de mettre en place une stratégie de tests pour le code API :

Des tests unitaires pour valider les parties métiers du code API (l’utilisation de JUnit devrait faire l’affaire, à vous de voir s’il y a besoin de faire des mocks ou non) 
Des tests d’intégration de l’API via un outil de tests d’API (ex : Postman, Soap-UI)
Pour les tests de l’application web et du batch, on verra dans un second temps. Je vous tiendrai au courant…

**Comment by josephherradi** [comment]
- Les tests unitaires utilisent une base de donnée H2 couplée avec le framework DBunit, pour lancer les tests:
mvn clean install
- Les tests des requêtes à l 'aide de postman se font avec l'import de la collection sur l'url (ou à l'ai de du json on PJ):
https://www.getpostman.com/collections/ea388b1a6a251d821bd6
